# Generated by Django 2.1.4 on 2019-02-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('banner_id', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('phone', models.TextField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('total_credit', models.IntegerField()),
            ],
        ),
    ]
