# Generated by Django 2.1.4 on 2019-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='banner_id',
            field=models.TextField(max_length=9),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_credit',
            field=models.TextField(max_length=9),
        ),
    ]
