# Generated by Django 2.1.4 on 2019-03-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20190301_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
