# Generated by Django 2.2rc1 on 2019-03-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20190302_1949'),
        ('students', '0011_auto_20190302_0725'),
    ]

    operations = [
    ]
